# Generated by Django 4.2.7 on 2023-12-24 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbankaccount',
            old_name='accnout_no',
            new_name='account_no',
        ),
    ]
