# Generated by Django 4.2.7 on 2024-02-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userbankaccount_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccount',
            name='bankrupt',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
