# Generated by Django 4.2.7 on 2024-02-04 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userbankaccount_user'),
        ('transactions', '0003_alter_transaction_transaction_type_trasnferbalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trasnferbalance',
            name='amount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amount', to='accounts.userbankaccount'),
        ),
    ]
