# Generated by Django 4.2.7 on 2024-02-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_bankrupt_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankrupt',
            name='bankrupt',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
