# Generated by Django 4.2.7 on 2024-02-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_alter_bankrupt_bankrupt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankRupt',
        ),
        migrations.AddField(
            model_name='transaction',
            name='bankrupt',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
