# Generated by Django 4.2.7 on 2024-02-04 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_delete_bankrupt_transaction_bankrupt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='bankrupt',
        ),
    ]
